### ISSUE TITLE
Reasonable error message for paths exceedling windows max path limit

### ISSUE THREAD

**Issue by wgyalpo** [coolOrangeLabs/powerload-utilities#70]
Even though it is possible to implement support for long paths by changing the settings in the windows group policy as well as changing the manifest of assemblies (exe also) of the .net in the powerload utilities tools.
However, the DTU from Autodesk for importing and exporting bck packages currently doesn't support the long path. Thus, it doesn't make sense to implement and support the long paths in the powerload utilities tools.

**Comment by MarkusCool** [comment]
Add check for validation the (Vault) Path is not longer thatn 260 characters in the Validate.sql.

**Comment by MarkusCool** [comment]
The problem is that the DTU is not able to handle a "LocalPath" with more than 260 characters. As this is the location, where the file to import is found, it needs to be corrected before the BCP package is created.
It needs to be dicussed: We could import files with "LocalFullFileName" longer than 260 characters, but the validation then must state them as error.

**Comment by wgyalpo** [comment]
The  error message should be added for the Folder like what is currently done for Files.

**Comment by MarkusCool** [comment]
Validated in version v1.1.14093
